version: "3.9"
services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_INITDB_DATABASE=devops
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
    api-a:
        build: ./api
        environment: 
            - SERVERNAME=api-server-a
            - DB=mongo
            - USERNAME=root
            - PASSWORD=password
            - DATABASE=devops
            - PORT=5001
        volumes: 
            - ./api:/app
        depends_on: 
            - mongo
        command: npm run dev-server
    api-b:
        build: ./api
        environment: 
            - SERVERNAME=api-server-b
            - DB=mongo
            - USERNAME=root
            - PASSWORD=password
            - DATABASE=devops
            - PORT=5002
        volumes: 
            - ./api:/app
        depends_on: 
            - mongo
        command: npm run dev-server
    frontend:
        build: ./frontend
        ports:
            - 4200:4200
        depends_on:
            - servicebus
    servicebus:
        container_name: servicebus
        image: nginx:latest
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - api-a
            - api-b
        ports: 
            - 8080:80