version: "3.9"
services: 
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
    api:
        build: ./api
        ports: 
            - 3000:3000
        environment: 
            - DB=mongo
        volumes: 
            - ./api:/app
        depends_on: 
            - mongo
    frontend:
        build: ./frontend
        ports:
            - 4200:4200
        depends_on:
            - api
