version: "3.9"
services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_INITDB_DATABASE=devops
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
    api:
        build: ./api
        ports: 
            - 3000:3000
        environment: 
            - DB=mongo
            - USERNAME=root
            - PASSWORD=password
            - DATABASE=devops
        volumes: 
            - ./api:/app
        depends_on: 
            - mongo
        command: npm run dev-server
    frontend:
        build: ./frontend
        ports:
            - 4200:4200
        depends_on:
            - api
